export { canonicalizeOperations, } from "./diff/canonicalize.js";
export { formatResult, main, parseArgs } from "./cli/cli.js";
export { createApproveBreakingChangeCodeFix } from "./suppression/codefixes.js";
export { compileService } from "./cli/compile.js";
export { $approvedBreakingChange, $approvedUnversionedChange, findSuppressions, findUnversionedSuppressions, getSuppressions, getUnversionedSuppressions, } from "./suppression/decorators.js";
export { emitFindingDiagnostics } from "./suppression/diagnostics.js";
export * from "./diff/diff-engine.js";
export * from "./diff/diff-operations.js";
export * from "./diff/diff-types.js";
export { $lib, BreakingChangeStateKeys } from "./lib.js";
export { matchOperations } from "./suppression/match.js";
export { getOperationIdentity, identityKey, normalizePath, resolveOperationIdentities, } from "./diff/operation-identity.js";
export { resolveOrigin } from "./diff/origin.js";
export * from "./pipeline/orchestrator.js";
export * from "./pipeline/policy.js";
export { resolveFindingLocation } from "./pipeline/resolve-location.js";
export * from "./reporting/reporter-console.js";
export * from "./reporting/reporter-github.js";
export * from "./reporting/reporter-json.js";
export * from "./reporting/reporter-markdown.js";
export * from "./suppression/suppression-guidance.js";
export * from "./suppression/suppression.js";
export { isOperationIdentity, isServiceIdentity } from "./types.js";
export { buildComparisonPairs, buildPhaseAPairs, buildPhaseBPairs, createVersionedView, defaultVersionClassifier, enumerateVersions, } from "./pipeline/versions.js";
//# sourceMappingURL=index.js.map