name: "TypeSpec Suppressions - PR Comment"

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
  workflow_run:
    workflows:
      [
        "TypeSpec Suppressions - Analyze Code",
        "\\[TEST-IGNORE\\] TypeSpec Suppressions - Analyze Code",
      ]
    types: [completed]

permissions:
  actions: read
  contents: read
  issues: write
  pull-requests: write

jobs:
  typespec-suppressions-comment:
    if: ${{ github.event_name == 'pull_request_target' || github.event.workflow_run.conclusion != 'skipped' }}
    name: "TypeSpec Suppressions - PR Comment"
    runs-on: ubuntu-slim

    steps:
      # *** IMPORTANT ***
      # For workflows that are triggered by the pull_request_target event, the workflow runs in the
      # context of the base of the pull request. You should make sure that you do not check out,
      # build, or run untrusted code from the head of the pull request.
      - uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github

      - name: Install dependencies for github-script actions
        uses: ./.github/actions/install-deps-github-script

      - name: Sync PR comment
        uses: actions/github-script@v8
        with:
          script: |
            const { default: syncTypeSpecSuppressionsComment } =
              await import('${{ github.workspace }}/.github/workflows/src/typespec-suppressions-comment.js');
            return await syncTypeSpecSuppressionsComment({ github, context, core });
