name: "TypeSpec Suppressions - Set Status"

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - labeled
      - unlabeled
  workflow_run:
    workflows:
      [
        "TypeSpec Suppressions - Analyze Code",
        "\\[TEST-IGNORE\\] TypeSpec Suppressions - Analyze Code",
      ]
    types: [completed]

permissions:
  actions: read
  contents: read
  issues: read
  pull-requests: read
  statuses: write

jobs:
  typespec-suppressions-status:
    name: "TypeSpec Suppressions - Set Status"
    uses: ./.github/workflows/_reusable-set-check-status.yaml
    with:
      monitored_workflow_name: "TypeSpec Suppressions - Analyze Code"
      required_check_name: "TypeSpec Suppressions"
      overriding_label: "Approved-TypeSpec-Suppressions"
